### ISSUE TITLE
link the documentation somewhere in the main SEPAL interface 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#101]
Suggestion from @vogtpet.

For people that just enter the SEPAL website there is no link to the documentation that we are building. (https://docs.sepal.io/en/latest/). This work is moving forward pretty fast and some of the documentation sections cover basic usage of the platform. 

Could it be linked somewhere ?  like an interrogation point in the footer and/or a message when we first connect to the platform ?

**Comment by eriklindquist** [comment]
At the moment, when a user hovers over the SEPAL in the bottom left corner, when you click there you are taken to the github wiki site. Since that site is less developed, we could change that link now to go to the docs.sepal.io/en/latest site.

**Comment by 12rambau** [comment]
I'm in the process of merging the existing doc from there to the new docs.sepal.io website

**Comment by vogtpet** [comment]
If possible, please provide a visible icon (Documentation) on the left panel for example under the purple wrench icon. Having to hover over a certain location is only good for people who know where to hover, all other may only find this by coincidence or not at all. A clearly visible button is more intuitive imo.

**Comment by ingdanielguerrero** [comment]
Yes, I also back @12rambau idea, and as @vogtpet said, it's difficult to find it by chance.

**Comment by eriklindquist** [comment]
Why don't we just add a '?' icon that links to documentation on the left side of the screen in-line with the other functional icons?

**Comment by vogtpet** [comment]
yes, good idea! 👍

**Comment by 12rambau** [comment]
I like this idea as well

**Comment by cdanielw** [comment]
Added link - bottom left in the main menu. Will be in next release, tomorrow morning.
