### ISSUE TITLE
create a restoration tool

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#104]
**What is the name of your repository ?**  
https://github.com/12rambau/restoration_planning_module/

**The name of your dashboard app**  
Restoration planning tool (ALPHA)

**A short description of the app**  
restoration planning tool using a weighted-sum approach

**Is your module requiring a GEE account ?**  
yes

**Any comment you want to add**  
This module is still under construction but as @yfinegold suggested, it would be nice for ou partners to dynamically see the advancement in the dashboard. The maintainer check list is obviously empty as it's an `alpha` version so don't close the issue when the module is on the pushed to prod, I'll close it when everything will be done. As usual I would need the `release` branch on the prod env and the `master` on the test. the source is the `ui.ipynb` file at the root of the repo. 

Thanks in advance 

**maintainer checklist**  
- [x] Name is set 
- [x] Description set 
- [x] Comprehensive README 
- [x] 3 languages documentation files (can be empty)
- [x] The module works with the default available Python libs
- [x] Existence of a `release` branch 
- [x] check behaviour

**Comment by cdanielw** [comment]
Done, though both branches fail to start.
