### ISSUE TITLE
create a bfast gpu module

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#105]
**What is the name of your repository ?**  
https://github.com/12rambau/bfast_gpu

**The name of your dashboard app**  
bfast GPU

**A short description of the app**  
GPU implementation of the BFAST algorithm to analyse time series

**Is your module requiring a GEE account ?**  
yes

**Any comment you want to add**  
adding @lecrabe to notify him when the app will be ready on the dashboard.
As usual, `release` branch on prod and `master` on test env.
The doc will be added automatically when the issue will be closed (ref https://github.com/openforis/sepal-doc/pull/20)

**maintainer checklist**  
- [x] Name is set 
- [x] Description set 
- [x] Comprehensive README 
- [x] 3 languages documentation files (can be empty)
- [x] The module works with the default available Python libs
- [x] Existence of a `release` branch 
- [x] check behaviour

**Comment by cdanielw** [comment]
Done
