### ISSUE TITLE
Forest change mask (shiny) doesn't work

### ISSUE THREAD

**Issue by yfinegold** [openforis/sepal#106]
tagging @lecrabe for info. 
The forest change mask (shiny) doesn't load. It's also duplicated and we have a working jupyter notebook UI version that's working. Can we remove this app?

**Comment by cdanielw** [comment]
Is this app still there, and does it still need to be removed?

**Comment by lecrabe** [comment]
It is working for me, but we can take it out if nobody uses it. The overall clip module we proposed should replace all those anyway. Can remove from dashboard

**Comment by cdanielw** [comment]
It works again now.
