### ISSUE TITLE
use natural sorting for files

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#115]
## Describe the bug
the ordering of folder is only based on strings meaning that with numbered folders you get the following:

![Capture d’écran 2021-06-15 à 09 19 03](https://user-images.githubusercontent.com/12596392/122009892-d66cd580-cdba-11eb-9f7e-fada41c50ed1.png)

## Expected behavior

```
0
1
2
3
4
5
6
...
```

I don't know for groovie but it's called **natural sorting** in php and C++ and I'm 100% sure we can handle it ;-)

**Comment by lpaolini** [comment]
Natural sorting has been implemented and pushed to master.

**Comment by dfguerrerom** [comment]
@lpaolini, I don't know if you have implemented this in your last push, but in most of the file explorer applications, the folders and the files are displayed in two groups —generally, the folders on the top and the files at the bottom— both groups human-sorted, can we also do this here?

**Comment by cdanielw** [comment]
Not on macs. But in SEPAL? We have to discuss.

**Comment by 12rambau** [comment]
> Not on macs. 
 
I'm forcing my finder to do it ;-) 

Also I agree with @dfguerrerom  that would be a super nice addition as this is effectively the way Jupyter and Rstudio are displaying content.

**Comment by dfguerrerom** [comment]
@12rambau, you forgot sepal_ui modules:
![image](https://user-images.githubusercontent.com/12363250/144428616-7ec3c33f-4df4-4eab-bfea-c1ebcd9cab7a.png)

**Comment by 12rambau** [comment]
![Capture d’écran 2021-12-06 à 08 24 06](https://user-images.githubusercontent.com/12596392/144804528-862034c9-a72b-40ed-974d-bc7d5d592a01.png)

working on prod !
thanks
