### ISSUE TITLE
create a FCDM module

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#116]
**What is the name of your repository ?**  
https://github.com/12rambau/fcdm/

**The name of your dashboard app**  
Forest Canopy Disturbance Monitoring (FCDM)

**A short description of the app**  
Mapping all kind of canopy disturbances (natural or human induced) within (semi-)evergreen forests

**Is your module requiring a GEE account ?**  
yes

**Any comment you want to add**  
As usual, `release` on prod and `master` on test if possible
Please don't close the issue until I add the real documentation

**maintainer checklist**  
- [x] Name is set 
- [x] Description set 
- [x] Comprehensive README 
- [x] 3 languages documentation files (can be empty)
- [x] The module works with the default available Python libs
- [x] Existence of a `release` branch 
- [x] check behaviour

**Comment by cdanielw** [comment]
Added

**Comment by cdanielw** [comment]
Can this be closed?
