### ISSUE TITLE
No traceback is provided when a voila app fails

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#118]
**Is your feature request related to a problem? Please describe.**
When a voila app fails for any reason the only error message provided to the end user is the following : 

> There was an error when executing cell [5]. Please run Voilà with --show_tracebacks=True or --debug to see the error message, or configure VoilaConfiguration.show_tracebacks.

This is preventing developer to support end user and diagnostic the source of the bug. The current work around is to clone the repository on the user machine and launch the app in Jupyter. Forcing us to take over the user computer... not very nice. 

**Describe the solution you'd like**
As mentioned in the voila error message, the traceback could be display if the voila app is launched with the option  `--show_tracebacks=True`. If a developer has access to the latest traceback then debugging will be much easier. 

`voila <path-to-notebook> --theme=dark --show_tracebacks=True`

**Comment by 12rambau** [comment]
oh according to the doc I can do it myself (https://voila.readthedocs.io/en/stable/customize.html) by customizing the ui.ipynb notebook metadata. I'll test it on test it's promising

**Comment by cdanielw** [comment]
Maybe we can find a way to get logs for these events instead, and give the users a cleaner error message?

**Comment by 12rambau** [comment]
and how would an app developer would access these logs ? ideally my objective is to be able to debug users without having to call you or @lpaolini

**Comment by 12rambau** [comment]
instead of having them admin, could we create a log hidden folder and write information there? 
And from your side, you just have to do an error screen with the appropriate filters: 

"The application has failed please contact our team for more information"

a "details" chevron link to an expandable panel with the complete log traceback
