### ISSUE TITLE
Automate sign up

### ISSUE THREAD

**Issue by yfinegold** [openforis/sepal#119]
Would be great to automate the sign up to SEPAL and flag when someone tries to sign up with same email more than once.

**Comment by 12rambau** [comment]
Just to illustrate what we talked about last week: 
Line 9169, 9170, 9173 of the admin worsheet are the same personn that requested access to SEPAL 3 time in less than an hour. he also reached out on [Gis.stackexchange](https://gis.stackexchange.com/a/421386/154945) (this comment will surely be removed as it's not respecting the rules).

**Comment by eriklindquist** [comment]
Yes. This happens a lot. But we do state the process. At the moment sepal is very similar to how access to MODIS burned area products work (or worked, not sure now).

Anyway...


Erik Lindquist, PhD
Forestry Officer
National Forest Monitoring (NFM) Team
REDD+/NFM cluster, Forestry Department
Food and Agriculture Organization of the United Nations
Rome, Italy 00153
________________________________

**Comment by 12rambau** [comment]
Up and running thanks to @cdanielw and @lpaolini !
