### ISSUE TITLE
Collecting training data under the classification tool is not straight forward

### ISSUE THREAD

**Issue by teopista** [openforis/sepal#126]
The icon for manually collecting training data is not easily accessible if someone is not yet familiar with it.
I would suggest to make it accessible via the same tab when the pre-collected training data is loaded. Also if possible there needs to be a way to enable a user to save the collected data as a csv or other formats.

**Comment by 12rambau** [comment]
Hi teopista, 

I'm currently working on the doc of the classification recipe, I think it's make more sense to have the "on the fly" function (gathering points) outside of the parameter sections. I hope that with some documenting it will be easier to grasp it. 

On the saving issue. If you export your recipe, the json file contains all the collected points. They can then be exrtacted to any other use. (that will also be documented). 

@cdanielw could we think of a way to integrate an export point btn next to the export image ?

**Comment by 12rambau** [comment]
documentation is now completed: https://docs.sepal.io/en/latest/cookbook/classification.html#select-points.

the training data can also be exported from the parameter section: https://docs.sepal.io/en/latest/cookbook/classification.html#collected-reference-data
