### ISSUE TITLE
upgrade voila version to 0.2.11

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#128]
Would it be possible to upgrade the version of `voila` ?

The prod server is using: 

```
$ voila --version
0.2.10
```

And we've add a very handy feature to the version `0.2.11`. Voila can now render JS script and finally behave like a true website. I would need it to create custom widget that include copy/pasting fonctionnalities for example. 

From what I looked in the code it is set [here](https://github.com/openforis/sepal/blob/8a74bb0aa6e81336fd35d29a94374e968be450c3/modules/sandbox/docker/script/init_jupyter.sh#L26) without version number. I assume then that a rebuild will be sufficient.

**Comment by cdanielw** [comment]
It's 0.2.12 now.
