### ISSUE TITLE
How to ask for more quota?

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#129]
**Is your feature request related to a problem? Please describe.**
New SEPAL users are accredited with a 1$ quota by default, which sometimes could be enough for users that only use the predefined recipes or some modules. However, for others, this quota could run out so fast, and usually, they get frustrated because they have zero clues on how to ask for more budget, even more, in some cases, they don't know that can ask for more resources. For others, it could be even worst, they are in a middle of a process and they are in a different time zone from Rome, they will have to wait hours until some administrator can see their quota request.

**Describe the solution you'd like**
We could create a button inside the resource's dashboard to automatically give the user a predefined amount of quota (i.e. 5% of their current budget) without waiting for approval, so they can finish their process. Afterward, we could create a form in which they can ask formally for more monthly quota (without exiting from SEPAL, a form to communicate with admins from inside the platform).

**Comment by 12rambau** [comment]
I have the feeling that @lpaolini and @cdanielw have coded something for us : 

<img width="40%" alt="Capture d’écran 2021-11-01 à 13 44 12" src="https://user-images.githubusercontent.com/12596392/139673541-3ebfa35c-5631-4103-a8dc-01c57db3b0b2.png">
<img width="40%" alt="Capture d’écran 2021-11-01 à 13 44 04" src="https://user-images.githubusercontent.com/12596392/139673546-73a2908e-ff01-4f1e-a8bb-d7dd9ee63257.png">

@dfguerrerom I'll create the new translation keys you'll just have to correct my typos
