### ISSUE TITLE
Add SDG 15.4.2. Module to calculate MGCI

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#132]
**What is the name of your repository ?**  
https://github.com/dfguerrerom/sepal_mgci

**The name of your dashboard app**  
Mountain Green Cover Index

**A short description of the app**  
Calculates the SDG 15.4.2: Mountain Green Cover Index at national/sub-regional scale

**Is your module requiring a GEE account ?**  
yes

**Any comment you want to add**  
It doesn't require any new libs

**maintainer checklist**  
- [x] Name is set 
- [x] Description set 
- [x] Comprehensive README 
- [ ] 3 languages documentation files (can be empty)
- [x] The requirements.txt file have been updated
It doesn't need any third party app
- [x] Existence of a `release` branch 
- [x] check behaviour within a fresh venv

**Comment by 12rambau** [comment]
> The requirements.txt file have been updated
> It doesn't need any third party app

even though it doesn't require third party app, adding the requirements.txt will fix the lib versions (sepal_ui, gee) to avoid version problems in the future. I will create a PR but in general I suggest you to use the `module_deploy` command from `sepal_ui`. Note that this command only work if you start your repository from the `module_factory` one: https://sepal-ui.readthedocs.io/en/latest/tutorials/send-to-sepal.html#check-your-dependencies
