### ISSUE TITLE
Earth Engine is not working on Venvs

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#134]
**Describe the bug**
I'm testing the modules envs and it seems like there is a problem when initialize Earth Engine.

**To Reproduce**
I have tested it in two different environments and this is happening.
![image](https://user-images.githubusercontent.com/12363250/138107764-24fbaa30-a4ed-4c6a-baf4-c6379c1bd636.png)

**Comment by 12rambau** [comment]
> git+git://github.com/openforis/earthengine-api.git@v0.1.270#egg=earthengine-api&subdirectory=python

Is there any reason why you specified the egg folder name and subdirectory ?

**Comment by 12rambau** [comment]
>  But that would require to have the credentials file writable by the user, which I'm a bit hesitant about.

I'm always reluctant to let end user modify these files

I'll check my comprehension of pip `egg` and `subdirectory` keywords but from what I recall the one you set are the default one (egg name default is lib name which is here `earthengine-api/`) and default subdirectory is obviously where all python libs live -> `python/`

**Comment by cdanielw** [comment]
Can we close this issue?

**Comment by 12rambau** [comment]
not yet, unfortunately, it will be closed with 2.5.0

**Comment by 12rambau** [comment]
Fixed by https://github.com/openforis/sepal/commit/397af40adb88d2d452f6ff7d92513e17f52cca05

**Comment by 12rambau** [comment]
False joy... we ended up with a pipy error :
```
Collecting sepal-ui==2.5.0
  Downloading sepal-ui-2.5.0.tar.gz (778 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
sepal-ui depends on earthengine-api@ git+git://github.com/openforis/earthengine-api.git@v0.1.270#egg=earthengine-api&subdirectory=python
```

sepal_ui 2.5.1 revert to the original earthengine API. 

I changed the `requirements.txt` of the GFC wrapper (https://github.com/openforis/gfc_wrapper_python/commit/5eab81061ebeec032b8d7dd536eb5cb90146e13a) to test if it's sufficent. let's see in the next built.

**Comment by 12rambau** [comment]
It works. 

So the final solution is the following: 
- [ ] add the earthengine API branch in the requirements.txt file of the apps 
- [ ] update the deploy script 
- [ ] update the templates
