### ISSUE TITLE
display something on the map when the user look the center coordinate

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#136]
## context

Wen I click on the scale on the top right side of the screen I can see the center of the map and its coordinates. 
It's also available to copy paste all the value in different format. That's 100% useful in many situation.

<img width="1338" alt="Capture d’écran 2021-11-02 à 17 40 58" src="https://user-images.githubusercontent.com/12596392/139908582-ad275bf9-5cbd-4348-820f-77228f70dbb4.png">

## Problem

My time playing Counter Strike are long gone so I don't have a yellow circle drawn on my screen anymore, meaning that I don't know where is the center of the map (I can use the developer mode to find out but that would be sad).

Could it be possible to add something (square, arrow, cross....) to indicate the center to the user when this panel is open ?

**Comment by cdanielw** [comment]
This was a feature we added so users can show the same bounds you see on the SEPAL map in other tools, like the EE Code Editor. It sounds like you have a use-case we haven't considered. Can you explain why you want to see the exact center of the map?

**Comment by 12rambau** [comment]
Let's say I have a map on screen. when we click on this popup, coordinates are displayed on top and I would be happy to know where they are on screen (a marker, a crosshair...) only as an indication, that's just fancier, not sure it meet any specific usecase (as placing a point is already done in the search bar)

**Comment by lpaolini** [comment]
I've implemented it (5be58af56cbaf05eb40b6a3e2ef86b1ba7c93613).
