### ISSUE TITLE
the deletion tooltip is persistent after deleting a file

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#138]
## description

In the file manager if you select the trash-bin icon, now the confirmation is not in a popup anymore but in a tooltip (I like it a lot, that's less mouse movement). 

But then if I click on another file the tooltip is activated by default. 

Here is a gif to show it: 

![Enregistrement de l’écran 2021-11-17 à 18 36 20](https://user-images.githubusercontent.com/12596392/142253170-f1c173dc-3e5c-4d4e-bc07-6833021339ae.gif)

Is it a bug or a feature ?

**Comment by lpaolini** [comment]
Definitely a bug :-), now fixed on master.
