### ISSUE TITLE
change vector file manager app name 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#139]
**Describe the bug**
The current name and description of the vector file management is not inlined with its content anymore

**change parameter**
|             | current                              | expected                                                                       |
|-------------|--------------------------------------|--------------------------------------------------------------------------------|
| name        | File transfer management                         | Vector file manager                                                         |
| description | Interface to import file to SEPAL and export theme to Google earth engine | Manage vector files and their upload to Google Earth Engine |

**Comment by cdanielw** [comment]
Done
