### ISSUE TITLE
Improve the search bar

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#142]
I assume it's the same frame for every search fonction in the platform. 

A user complained that he was unable to find "seplan" using the search bar. It was indeed normal as the app name is "se.plan" with a `.`. It will be an issue for every ponctuation mark (" ", "_", "-", "."), could the regex search be imporved to ignore these characters ? 
![Capture d’écran 2021-11-26 à 15 10 39](https://user-images.githubusercontent.com/12596392/143593440-0d56e8ae-29bc-4c23-9297-f41e8f68021a.png)

**Comment by lpaolini** [comment]
I've pushed a fix to ignore non-alphanumeric characters when searching.
