### ISSUE TITLE
Export as csv in classification, file are misnamed

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#145]
In the classification recipe, you can export as a .csv the classification legend. This file will be called `<classif name>_legend.csv`. 
If the sample points are exported they are also named `<classif name>_legend.csv`. Could we use another name like `<classif name>_sample.csv` ?

**Comment by cdanielw** [comment]
Yes - good catch. I'll rename it to ${title}_reference_data.csv.

**Comment by cdanielw** [comment]
Fixed on master
