### ISSUE TITLE
see recipe type when selecting a recipe for classification (or other recipes that ingest recipe)

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#149]
That's a lot of recipe for an issue title... let's take the example of classification for simplicity.

When I enter the Classification functionality SEPAL asks to select an Image to classify. One option is to select an EE image, the other a recipe. In the dropdown selector, all the recipes are displayed without any information. Problem: they are not all compatible with the classification recipe (I tried with a TS that simply crashed it). In the SEPAL recipe list, each one of them is set with the type on top so we suggested to users (in doc and webinars) to not write image type in titles. but that can lead to difficulties to identify who's who in the dropdown:

![Capture d’écran 2021-12-06 à 08 27 10](https://user-images.githubusercontent.com/12596392/144805384-f2b6becf-b251-4023-88bb-eb0d68632999.png)

Would it be possible to add subheaders in the dropdown and order them by type ? As an example this is what we are doing in sepal_ui for the assets:
![Capture d’écran 2021-12-06 à 08 33 11](https://user-images.githubusercontent.com/12596392/144805586-8987aa8a-5c83-45ca-b9c8-b791a9d12146.png)

If you consider going down this path could it be possible to limit the "selectable" recipe to the types compatible with the recipe ?
e.g. for classification, exclude other "classifications", "TS", and "CCDC".

**Comment by cdanielw** [comment]
We have planned to move away from a combo box for recipe selection to a separate panel. It will have different filtering and sorting options. This will come when we implement functionality for organizing recipes. 

I'll go though and filter out unsupported recipes from the selections now though. TS and CCDC - they're different as they don't produce any regular image. We always want to exclude current recipe too. Using classifications for classifying, why not? I can imagine using probability bands from one classification to generate another one.

**Comment by 12rambau** [comment]
this is now covered for some of the recipes and with the project functionality is way easier to follow the recipe list. I think we can safely close this one.
