### ISSUE TITLE
unable to launch se.plan

### ISSUE THREAD

**Issue by abczefg** [openforis/sepal#150]
It always took me long time to launch the app: many times fail to launch before I could launch it successfully. I saw another person raising the same issue in se.plan. Therefore I saved the log so you could inspect.

I was using t2 instance most of the time. 

[sepal.io-1638789900665.log](https://github.com/openforis/sepal/files/7660504/sepal.io-1638789900665.log)

**Comment by 12rambau** [comment]
could you let us know if you're experiencing the same when launching a `t2` or even a `m2`? 
maybe the application has grown too big to be handled by our smallest instance.

**Comment by 12rambau** [comment]
@abczefg are you still experiencing this issue ? I'm not able to reproduce the behaviour you described from my end

**Comment by abczefg** [comment]
@12rambau  recently this is no longer happening, I have no problem launching the app  :)
