### ISSUE TITLE
problem with class display vizualization when unzoom

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#151]
## Describe the bug
When a classification is displayed and the image is unzoomed a lot, the AOI becomes nearly fully black. 

![Capture d’écran 2021-12-06 à 15 02 35](https://user-images.githubusercontent.com/12596392/144859791-eac6a682-0428-434c-beda-4820e93899d0.png)

## To Reproduce

display the following asset in any recipe: `users/bornToBeAlive/sepal_ui_test/imageViZExample` and display the class preset vizaulization parmaters. You should see the following: 

![Capture d’écran 2021-12-06 à 15 02 27](https://user-images.githubusercontent.com/12596392/144859963-e9345381-bc82-4366-ba5d-461c7da0d927.png)
 
Unzoom a lot and you'll see the first one. 

## Expected behavior

Based on the script that create the vizparams, the palette is paded as such: 
```javascripts
    var paddedPalette = sequence(minValue, maxValue).map(function () {
      return '#000000'
    })
    values.forEach(function (value, i) {
      paddedPalette[value - minValue] = palette[i]
    })
```

meaning that every value between the values will be displayed as black. That could be a feature, forcing the user to zoom in. If that's not the case would it make sense to fill the "in-between" values of the palette with the previous one instead of black?

**Comment by cdanielw** [comment]
Which pyramiding policy was the asset exported with?

**Comment by cdanielw** [comment]
It looks like mean - you want to use mode or sample when exporting categorical bands.

You have this issue directly in ee:
https://code.earthengine.google.com/2018f4ce94e2c8bfb1fa37a8421eefa6

**Comment by cdanielw** [comment]
You can do something like this to re-export it. That will give the class band a pyramiding policy of `mode`, while the rest of the bands are `mean`. You'll probably want to specify a bunch of other export properties too.
```
Export.image.toAsset({
  image: i, 
  pyramidingPolicy: {
    '.default': 'mean',
    'class': 'mode'
  }, 
})

```

**Comment by 12rambau** [comment]
I aggree that pyramiding policy of this asset is `mean` and that it should be `mode`.

@cdanielw you are the one that provided me with this asset so can you confirm that any categorical asset created by SEPAL will use mode pyramiding policy ?

**Comment by cdanielw** [comment]
SEPAL export the class band in classifications in mode. I do have to verify that I specify pyramiding policy properly for  categorical bands in index change and class change recipes though.

The asset I provided you with has the class band in mode: `users/wiell/forum/visualization_example`
The one you used probably has the class band in mean: `users/bornToBeAlive/sepal_ui_test/imageViZExample`

Check out the script in my previous comment.

**Comment by cdanielw** [comment]
Lucky you raised this - it turns out I didn't specify the pyramiding policy for index changes and class changes.

**Comment by 12rambau** [comment]
perfect the issue wasn't useless after all. 
Happy to help!
