### ISSUE TITLE
Values inspector tool shows an undesired overflow bar

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#153]
**Describe the bug**
When I activate the values inspector in the optical mosaic recipe, the values are showing undesired overflow x-y bars, I've tested in three different explorers and this is happening on Chrome and MS Edge.

**To Reproduce**
1. Use Google Chrome Version 96.0.4664.45 or MS Edge
2. Create any recipe
3. Use the value inspector

**Expected behavior**
Deactivate the overflow bars.

**Screenshots**
![image](https://user-images.githubusercontent.com/12363250/145091376-3379311e-c6b5-43f1-8e92-d645b8c201b8.png)

**Comment by cdanielw** [comment]
Maybe you can have a look at this, @lpaolini ?

**Comment by lpaolini** [comment]
Fixed and committed to master.
