### ISSUE TITLE
change vector file manager description in the app dashboard 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#156]
The module behaviour has changed a lot since its beginning. It is now able to create grid on the fly and download table files to the SEPAL environment. @lecrabe and I think that the naming and description should change accordingly.

Can you update the dashboard with the following modification ?

|             | current                                                     | desired                                                                                         |
|-------------|-------------------------------------------------------------|-------------------------------------------------------------------------------------------------|
| title       | Vector file manager                                         | /                                                                                               |
| description | Manage vector file and their upload to Google earth Engine  | Tool to manage vector files in SEPAL (upload, download, export to GEE and grid generation) |

**Comment by cdanielw** [comment]
Done
