### ISSUE TITLE
impossible to load 2 legend successively

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#157]
**Describe the bug**
If you load a legend in sepal after and then decide to use another one (loading it from another file), the "apply button is never released, preventing the user to validate the new legend.

Currently the only solution is t manually remove all the existing class and once the field is empty you can reload a new file.

**To Reproduce**
I'll chare here 2 csv file, load them in any order, the second one will not work 
[copernicus_esa_legend.csv](https://github.com/openforis/sepal/files/7687161/copernicus_esa_legend.csv)
[legend_esa_sepal.csv](https://github.com/openforis/sepal/files/7687162/legend_esa_sepal.csv)

**Comment by cdanielw** [comment]
I'm unable to reproduce this anymore. Can you please check on the test server?

**Comment by 12rambau** [comment]
I'm unable to reproduce it either, maybe it has been solved as a side effect of the latest modifications....

I'll close it for now
