### ISSUE TITLE
Remove Zonal analysis module

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#163]
This module is completely obsolete and it was developed for the sole purpose of a CIRAD mission. It works on very few countries and only for a small subset of data. The code will remain available for anyone interested but it should not stay in the SEPAL dasboard. 

| repository                                  | name           |
|---------------------------------------------|----------------|
| https://github.com/openforis/zonal-analysis | zonla analysis |

**Comment by cdanielw** [comment]
Removed.
