### ISSUE TITLE
install Sen2Cor application 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#165]
Sen2Core is a SNAP plugin from ESA: https://step.esa.int/main/snap-supported-plugins/sen2cor/

> Sen2Cor is a processor for Sentinel-2 Level 2A product generation and formatting; it performs the atmospheric-, terrain and cirrus correction of Top-Of- Atmosphere Level 1C input data. Sen2Cor creates Bottom-Of-Atmosphere, optionally terrain- and cirrus corrected reflectance images; additional, Aerosol Optical Thickness-, Water Vapor-, Scene Classification Maps and Quality Indicators for cloud and snow probabilities. Its output product format is equivalent to the Level 1C User Product: JPEG 2000 images, three different resolutions, 60, 20 and 10 m.

It would be useful if we want to integrate some Sentinel 2 images manipulation out of GEE.

**Comment by cdanielw** [comment]
I unfortunately cannot find an easy way to get the default config working. They're installed in the installing user's home directory, which is in this case. I can move it into /etc, but that still would require the config path to be included in every request.

**Comment by 12rambau** [comment]
That's for pr. Baltzer alert system (IMPRESS project) so that will do just fine
