### ISSUE TITLE
Add 'Restoration' tag for module grouping 

### ISSUE THREAD

**Issue by yfinegold** [openforis/sepal#168]
Add the tag "Restoration" to the tags of the modules (along with Tools, Time series, Inventories, Planet, SMFM, Disaster) with the modules 'SDG indicator 15.3.1', 'SDG 15.4.2', 'Soil moisture mapping', 'BFAST GPU',  'se.plan', 'CUSUM change detection', 'GWB analysis', 'Time series clip' under the tag

**Comment by 12rambau** [comment]
By doing that some of the modules will embed 2 or more tags is it a wanted feature?

**Comment by eriklindquist** [comment]
I think it is OK to have 2 or more tags per module.

Erik Lindquist, PhD
Forestry Officer
Forestry Division
Food and Agriculture Organization of the United Nations
Rome, Italy 00153
________________________________

**Comment by yfinegold** [comment]
@eriklindquist would it be possible to add this tag to the SEPAL dashboard?

**Comment by cdanielw** [comment]
Done.
