### ISSUE TITLE
I can select TS recipe as input in the classification tool

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#169]
In the classification tool, if I select an image from a saved recipe, every recipe will be displayed including TS. 
the only available band is `none` and I didn't go through the whole process but I'm pretty sure it's not going to end well.

![Capture d’écran 2022-01-28 à 13 44 36](https://user-images.githubusercontent.com/12596392/151549216-b17cb98c-02f6-4541-a896-d8887d0cfb72.png)

Would it be possible to restraint the available recipe?

**Comment by cdanielw** [comment]
Resolved by 2231b440e2a7f80d23c84e120270a3625fc24aedy.
