### ISSUE TITLE
When I change training data type after selecting a file, the menu does not change

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#170]
**step to reproduce**

In the classification tool when data are added to the training data, multiple methods are available: 

- csv file
- EE table
- saved sepal recipe
- sample from existing classification

Let's say I want to select them from a csv file. I click csv file, then select a csv and I'm moved to panel 2 which is the column selection panel. I finally realized that I was'nt supposed to do that but instead a sample from existing classification. I go to the dropdown menu at the top of the popup window and I click on "sample from existing classificaiton". Then the view in the window remains the same wich should'nt be the case: 
![Capture d’écran 2022-01-28 à 16 18 13](https://user-images.githubusercontent.com/12596392/151573636-8807dc3f-52bb-4cbf-81ec-ad0ebd43bbec.png)

**Expected behaviour:** 

I would expect the tool to reset my selection and go back to the first page when I select a new method (more or less the same behaviour as the cancel btn).

**Comment by cdanielw** [comment]
Resolved in 6569dc64b9d2ac3a3193d583a7499b5ee74e2846.
