### ISSUE TITLE
planet mosaic dates are badly set up

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#172]
2 things here: 

**design**: On safari, XL screen, the date tab is not align with the DAT btn
**init**: default start date is today, default end date is 1 year in the future. shouldn't it be from 1 year in the past to today instead ?

![Capture d’écran 2022-02-01 à 08 10 47](https://user-images.githubusercontent.com/12596392/151926545-4b2c4687-4520-4ae0-acbb-c8ee8649d579.png)

**Comment by cdanielw** [comment]
Resolved by e93851ba1f73e3f43b19ddc7633d9a26eb759238.
