### ISSUE TITLE
Time Series Clip error

### ISSUE THREAD

**Issue by kdyson** [openforis/sepal#173]
**Describe the bug**
When I try to use the Time Series Clip (Beta) tool, I instead get the following error: There was an error when executing cell [4]. Please run Voilà with --show_tracebacks=True or --debug to see the error message, or configure VoilaConfiguration.show_tracebacks.

**To Reproduce**
1. Go to 'Apps'
2. Click on 'Time Series Clip (Beta)'
4. See error "There was an error when executing cell [4]. Please run Voilà with --show_tracebacks=True or --debug to see the error message, or configure VoilaConfiguration.show_tracebacks."

**Expected behavior**
The tool to load.

**Screenshots**

**Comment by 12rambau** [comment]
With the latest release of SEPAL the version of GDAL changed and apps that require Pygdal needed a refactoring of requirements. 
It is solved from my side, let me know if you manage to start it from yours
