### ISSUE TITLE
SEPAL cannot load image with a "vizualization" property

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#174]
**Describe the bug**
When a GEE layer is used in a Map and this layer embed a "Vizualization" property then the function crash as some of the keys cannot be found

**To Reproduce**
Go to any recipe, add an extra layer and use the following: "USGS/SRTMGL1_003" (that 's the NASA 30m res elevation layer). It will crash. 

I think it's because the "type" prop is missing : 

```python
{
    "visualization_0_bands": "elevation",
    "visualization_0_gamma": "1.6",
    "visualization_0_max": "6000.0",
    "visualization_0_min": "0.0",
    "visualization_0_name": "Elevation"
}
```

**Comment by cdanielw** [comment]
Resolved in 42f6bd05b3eca4610f87596b7114a88322e19db5.
