### ISSUE TITLE
the build ID is not displayed anymore

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#185]
**Describe the bug**
The build was previously displayed in the bottom-left corner and is now only displaying "?" as shown on the screenshot.

**To Reproduce**
hover "SEPAL" in the bottom-left corner

**Expected behavior**
the build and commit name used for the currently running server.

**Screenshots**
![image](https://user-images.githubusercontent.com/12596392/168543692-9128b1d4-8c85-4d5c-aa89-fbd1a1102472.png)

**Comment by cdanielw** [comment]
Resolved in https://github.com/openforis/sepal/commit/13338c573b6fdb255d00f5eb418997249a63465b
