### ISSUE TITLE
cannot restart a Jupyter session

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#186]
## Describe the bug
When the jupyter session is destroyed from the insode of the JupyerNotebook application, it's then impossible to start a new one.

## To Reproduce
- start an instance
- open JupyterNotebook application 
- click the "quit" btn in the topright corner 
- Server are now stopped for both JupyterLab and JupyterNotebook
<img width="1480" alt="Capture d’écran 2022-06-02 à 17 00 07" src="https://user-images.githubusercontent.com/12596392/171661136-2b60104c-f42e-40f0-9cd4-458b87d5e5b7.png">
<img width="1480" alt="Capture d’écran 2022-06-02 à 17 00 13" src="https://user-images.githubusercontent.com/12596392/171661155-242c8a48-343f-43e8-b156-6577810a08c0.png">
- if you launch again JupyterLab application the server will not restart 
<img width="1480" alt="Capture d’écran 2022-06-02 à 17 03 53" src="https://user-images.githubusercontent.com/12596392/171661283-c5efb010-69b2-4252-89c1-ce3d3a45caf7.png">
- the only solution is to start a new instance
   
## Expected behavior
I would expect SEPAL to check the server existence and start a new one if necessary

**Comment by cdanielw** [comment]
Resolved by https://github.com/openforis/sepal/commit/88b7291efd3336cefcd9c31254676cf9bd86e72b
