### ISSUE TITLE
Would it be possible to only sample in the image in classification ? 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#211]
**Is your feature request related to a problem? Please describe.**
When creating a classification, you have the option to sample training data from an existing classification. you select the asset, the number of samples per class, and the scale. Then these samples are selected within the total footprint of the "already classified image". but sometimes this initial image is way bigger than the area covered by the "to be classified images". Would it be possible to only sample within the total footprint of the images I want to classify? 

Here is an example where I sample in the CCI map that covers the whole of Zambia when I only need the eastern province. creating the Zambian asset is nice as it can be used in any district but the number of useless sample points is huge. 

<img width="1340" alt="Capture d’écran 2022-08-03 à 09 27 22" src="https://user-images.githubusercontent.com/12596392/182549476-31b3f21a-5e91-4b76-9c70-a299ada8931a.png">

**Comment by cdanielw** [comment]
Resolved in https://github.com/openforis/sepal/commit/55b72c1c9ed9ab319105fce6fcd6da00f2d13c22.

- Sampling of a categorical EE asset will be done only in the classification recipe AOI. 
- Any reference data not intersecting the bounds of the AOI will be filtered out. Doing an intersection with the actual AOI was too inefficient.
