### ISSUE TITLE
fix version of proj and gdal in the environment

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#214]
This is not exactly a bug but more of a remark about the SEPAL environment. 
Applications are living in a Linux environment that is already hydrated with many libs packages and softwares. That is awesome as anybody can jump here and start coding geospatial stuff without thinking of the burden of installing some of the most *%£$$$ linux packages I've ever seen. 

I'm of course pointing at [GDAL](https://gdal.org) and [PROJ](https://proj.org/index.html). 

The main issue here is every time SEPAL is rebuilt, the version of one (or both) of these package is suceptible to change putting at risk all the libs that are depending on it. this list is not exhaustive but in our requirements there is `rgdal`, `localtile` (until I finish working on https://github.com/girder/large_image/issues/898), `gdal`, `pygdal`, `pyproj` ... etc 

Do we really need to have the latest one ? 
Could we instead pin them to a specific version and update them once in a while to ensure that everything in SEPAL continues working until we really want to change?

**Comment by cdanielw** [comment]
Resolved in https://github.com/openforis/sepal/commit/28b7aa91b43bc69d8e5d4d468978ad4f9363a1b2
