### ISSUE TITLE
the viz band selector disapear after 3s

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#222]
**Describe the bug**
When I want to select the band visualization options if I open the dropdown and start to scroll the popup closes after 3s.
After some tests this timeout is starting after I hover any component of the popup (not only the dropdown). That is critical when for example looking for a band in a CCDC asset (as you need more than 3s to scroll through everything. 

**Expected behavior**
Could you simply remove the timout, this is the only component of the map that has one it's very disturbing

**Screenshots**
![image](https://user-images.githubusercontent.com/12596392/184810328-71c10199-a632-44fe-be1f-4d68ae99df80.png)

**Comment by cdanielw** [comment]
Fixed.
