### ISSUE TITLE
the with of the column selection is too small

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#227]
When creating a classification I wanted to use the FREL 2020 results as an input. the raw data are using as column values the real name of the classes i.e. "Grassland", "Cropland" .... 

I select the file, I select the column and then I need to select the value for each legend item. I click on the rounded + and then instead of the name I only see the first letter, badly cut (make it difficult to differenciate "C" and "G"). 

I think the dropdown width is bound to the parent field which is a problem if column name is bigger than 1 character. Would it be possible to free it ? 

<img width="1339" alt="Capture d’écran 2022-08-22 à 12 34 04" src="https://user-images.githubusercontent.com/12596392/185901911-2bfa0ebf-6ed9-440e-bde6-71741039765e.png">

**Comment by cdanielw** [comment]
Fixed.
