### ISSUE TITLE
display of out of bounds date in alert change 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#228]
If you display the dates from the change alert recipe, everything bigger than the end of monitoring dates is displayed in red which is very confusing. Don't you think it would worse the shot to mask them ? 
<img width="1341" alt="Capture d’écran 2022-08-25 à 13 29 19" src="https://user-images.githubusercontent.com/12596392/186661539-e87de967-9bb2-43ec-b075-b9b7f6d762dd.png">

**Comment by cdanielw** [comment]
Maybe we could add an additional option in the layer visualization panel, to mask out-of-bound values? That option could be enabled by default for these layers.

**Comment by 12rambau** [comment]
right it would be nice, but in this case I would more expect nodata value for places without alert both in the display and the export.

I didn't mentioned it in the issue message, but here I think the most urgent matter is the inversion of the bar and the bug in reading the values on the map (when you hover it's always nodata)

**Comment by cdanielw** [comment]
Resolved by 8e81047fdb27ec2143497ec39daba161b79a2110b.

**Comment by cdanielw** [comment]
Resolved by https://github.com/openforis/sepal/commit/8e81047fdb27ec2143497ec39daba161b79a2110b
