### ISSUE TITLE
recaptcha widget is displayed between `tools ` swap

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#238]
The ReCaptcha widget is displayed in the background of the sepal tools in the bottom right corner as is shown in the below image

![Untitled video - Made with Clipchamp](https://user-images.githubusercontent.com/12363250/193231322-7ee16d80-d8ad-4503-82d4-f92e39887158.gif)

**To Reproduce**

1. Go to sepal and swap between the tools (process, files, terminal...)
2. check the bottom right corner and see the overlayed widget

The behavior is happening on Chrome but not on Firefox

**Comment by cdanielw** [comment]
Resolved by https://github.com/openforis/sepal/commit/b90d58387a9770703e15aa24d856a57d44674d60.
