### ISSUE TITLE
ipyvuetify widgets are not displayed after last release

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#239]
I posted this issue and the findings in https://github.com/12rambau/sepal_ui/issues/599, apparently, the problem is not only related to the versions, I've tested old virtual environments, and even though the widgets are not displayed in `jupyterlab` they are rendered without problems when using `voila`, so... we are safe. 
Reading https://github.com/jupyter-widgets/ipyleaflet/issues/889, this issue could be related to a newly installed extension that might be causing the problems, did we install a new one?

**Comment by 12rambau** [comment]
That's a very bad news indeed, I will have a look on Sunday as I have a bit of time. 
Is it on Prod or test ?

**Comment by dfguerrerom** [comment]
Yes it is on prod.

**Comment by dfguerrerom** [comment]
And update on this:
widgets are not rendered even in voilá when using ipyvuetify==1.8.4 and ipywidgets==8.0.2, if the `venvs` of the venvs are updated, we have to be sure that are using these versions.
ipyvuetify==1.8.2
ipywidgets==7.6.5
At least while we find a definitive solution

**Comment by dfguerrerom** [comment]
fixed with [bfc043a](https://github.com/openforis/sepal/commit/bfc043ab3cab69753676cd7f6c384d529f9a19d9)
