### ISSUE TITLE
extra applications are relying on GEE

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#254]
In the application dashboard, users can open the Soil and Moisture application even without being connected to GEE. The application is actuallly depending on it wich leads to the bug described in the forum here: https://groups.google.com/g/sepal-users/c/EC3CudEdGJQ/m/_wCKAACEAwAJ?utm_medium=email&utm_source=footer

@cdanielw could you add it to the list of GEE dependent apps ? 

EDIT: 
adding the other applications that could lead to the problem and waiting for @dfguerrerom intputs as he's the maintainer of the applications

- sdg 15.4.2
- soil and moisture

**Comment by cdanielw** [comment]
I updated sepal_pysmm.
