### ISSUE TITLE
can we update gdal?

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#258]
First of all, my apologize for requesting that.

As it was reported in https://github.com/openforis/sepal/issues/245, there are some Sepal Contrib modules that require Numpy array support (https://github.com/sepal-contrib/sepal_pysmm/issues/25 or https://github.com/sepal-contrib/sepal_smfm_biota/issues/42) .
The problem: this support is not granted in the current way as we install the virtual enviroments, GDAL requires Numpy to be installed prior its installation, if it doesn't find it, it skips the Numpy Array support, causing the `No module gdal_array_` error, and, as we cannot manage the order of the installation it will always fail, no matter how we sort the `requirements.txt` file.

The good new: there is a patched version that allows set numpy as requirement of gdal installation, it was mentioned here: https://github.com/OSGeo/gdal/issues/5844#issuecomment-1145860934.

Do you think we can move to a gdal>=3.5.0.3 ?

Thanks

**Comment by 12rambau** [comment]
😭 not again 😭 
That's official I hate GDAL forever. 

Let me know when/if it's in prod, I'll need to update all the venvs of the currently running applications

**Comment by dfguerrerom** [comment]
Some users are still reporting errors in soil moisture app which is relying on GDAL to work: https://groups.google.com/g/sepal-users/c/b8nxS4FJz78/m/3fH7NaqcAgAJ?utm_medium=email&utm_source=footer&pli=1
