### ISSUE TITLE
cannot zoom in/out when using polygon as AOI

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#261]
**Describe the bug**
I was trying to create an AOI using the `polygon` tool in the "planet recipe" and the zoom in/out didn't work, I also tested it on a different environment using the "optical mosaic" and it didn't work either.

**To Reproduce**

1. open the planet recipe, or any, the problem is spread across all recipes.
2. select `Polygon` as AOI tool.
3. zoom in/out
4. will fail

**Comment by lpaolini** [comment]
Fixed in f4c8366172271bb8545134635bda6ec9ca3babf6.
