### ISSUE TITLE
se.plan should require GEE

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#279]
**Describe the bug**
If a user has not connected his GEE account to SEPAL, he can still open se.plan application. Which leads to the following error: 
![WhatsApp Image 2023-04-20 à 15 51 49](https://user-images.githubusercontent.com/12596392/233402175-cd429998-2416-4020-bfcd-ba2bd9137e1d.jpg)
 

**Expected behavior**
se.plan should be in the list of the application requiring GEE connection

**Comment by cdanielw** [comment]
Fixed.
