### ISSUE TITLE
not able to export to sepal workspace

### ISSUE THREAD

**Issue by teopista** [openforis/sepal#282]
Exporting a mosaic (tested with optical mosaic) to sepal workspace gives an error below

{
  "id": "4a1ac8f9-214d-47e5-8527-f3dece54f64b",
  "recipeId": null,
  "name": "Retrieve Bugoma_NDVI_dif-19-23 to SEPAL workspace",
  "status": "FAILED",
  "statusDescription": "{\"defaultMessage\":\"Failed to execute task: \",\"messageKey\":\"tasks.status.failed\",\"messageArgs\":{\"error\":\"ServerException: Failed to set band names.\"}}"
}

Thank you!

**Comment by 12rambau** [comment]
Hi Teopista is it an old recipe or an old one ?

**Comment by teopista** [comment]
New one!

**Comment by 12rambau** [comment]
then @cdanielw do you have access to the log directly from here ?

**Comment by cdanielw** [comment]
I believe you still actually got the image downloaded, but it failed to set some metadata on the image. So it's a GDAL related bug I'll have to check.
