### ISSUE TITLE
add localtileserver virtual environment 

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#285]
As it was pointed on https://github.com/12rambau/sepal_ui/pull/835, `localtileserver` now supports `rasterio`, to make it work in our SEPAL environment without extra user steps, we have to add this environment variable to all users:

`LOCALTILESERVER_CLIENT_PREFIX="/api/sandbox/jupyter/proxy/{port}"`

**Comment by 12rambau** [comment]
fixed in https://github.com/openforis/sepal/commit/2164df1a3614d534999b257b8fcfd2a38ea02718
