### ISSUE TITLE
add the option to pause the live rendering

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#289]
It can sound strange as it's one of the most fun feature of SEPAL but .... Now that GEE is not free anymore for most of us, it will be become extremely expensive to connect a commercial GEE account to SEPAL as any live renderenring (yes I'm speciffically thinking of you in the back, zooming in and out just because it's cool) is requesting tiles hence computation to GEE. 

I was thinking of an option, either set globally at the user level or a project option, to check or uncheck to activate the live rendering. 

And in case it's not performed live add an extra button on the top-right side of the pannel to launch "render" (it could also be called "request").

**Comment by cdanielw** [comment]
Implemented. There's an option under the user details
