### ISSUE TITLE
Not able to connect to GEE

### ISSUE THREAD

**Issue by CatalinVulcan** [openforis/sepal#290]
I'm doing all steps necessary as mentioned [here](https://docs.sepal.io/en/latest/setup/gee.html).

Yet, after giving permission for Sepal to connect to GEE and being redirected back, Sepal isn't connected to GEE.

Any ideas?

**Comment by dfguerrerom** [comment]
Can you confirm you're still having this issue? 
When you say "Sepal isn't connected to GEE" is it because you still see "disconnected" in your user profile settings?

**Comment by CatalinVulcan** [comment]
I'm still having the same issue.
Yes, I still see Disconnected after going through the process, while there's no error message or anything indicating this error.

I do Account name > User details > Google account > Connect your Google account > Choose an account > Allow > Redirect back > Still disconnected

**Comment by dfguerrerom** [comment]
Can you check that you don't have any other sepal tab/session open? please double-check it, and don't forget to check any other device where you might have opened sepal.io.

Sometimes if you have multiple windows open, the validation system creates a conflict and doesn't update the GEE state.

**Comment by cdanielw** [comment]
We have added the ability to select Google Cloud Project to use with EE. This should sort this issue out.
