### ISSUE TITLE
upgrade python version

### ISSUE THREAD

**Issue by TmtStss** [openforis/sepal#297]
The current version of python on Sepal is 3.8.10. Is there a plan to upgrade to a newer version ?

**Comment by 12rambau** [comment]
Sepal is running instances on Ubuntu 20.04 that is shipping Python 3.8. 
I think the easiest way to update would be to move toward Ubuntu 22.04.

**Comment by TmtStss** [comment]
Thanks for the clarification. Is it in the pipeline ?

**Comment by cdanielw** [comment]
I'm working on it as I'm writing this.  It will take some time until we can roll this out, as we have to test this properly first. Once released it'll probably be v3.10.12.

**Comment by cdanielw** [comment]
That is correct. Thanks for the heads-up.

**Comment by TmtStss** [comment]
Quick note: the [SEPAL documentation](https://docs.sepal.io/en/latest/cli/python.html) is still mentioning Python 3.8.
