### ISSUE TITLE
Jupyter lab 4 (on sepal jellyfish) breaks ipyleaflet traits

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal#304]
As it was reported initially on: https://github.com/jupyterlab/jupyterlab/issues/14829, some `ipyleaflet` traits are broken with `jupyter lab 4`... this will cause some of the tools developed with this python package to experience unexpected behaviors, such as not updating bounds or modifying the map zoom levels.
I post it here just to keep track of the development of one solution.

related topics
- https://github.com/jupyter-widgets/ipyleaflet/issues/1125
- https://github.com/jupyterlab/jupyterlab/issues/14829

**Comment by 12rambau** [comment]
while this is worked on from ipyleaflet side, do you think it would be possible to pin the Jupyterlab version here: https://github.com/openforis/sepal/blob/e2f0d5b94eb0ba13939fd6d154da2d5391a86572/modules/sandbox/script/init_jupyter.sh#L18

**Comment by dfguerrerom** [comment]
Until `ipyleaflet` for jupyterlab 4 is updated, we'll use @cdanielw fork: https://github.com/cdanielw/ipyleaflet with the fix.
