### ISSUE TITLE
Cannot register new users

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#311]
I wanted to add new users to the platform to perform EUDR evaluations but the registration process seems broken. 
I checked with a dummy email address and I confirm that I cannot set my password. I cannot say if it's the password that is not updated or SEPAL that fails to compare the form with the database. 

In any case, existing users still work. 

The bug from a user POV: 

<img width="567" alt="image" src="https://github.com/openforis/sepal/assets/12596392/d79f09aa-a1ec-48bd-9868-de10c4a38e7e">

**Comment by cdanielw** [comment]
This is sorted out.

**Comment by 12rambau** [comment]
thanks @cdanielw and @lpaolini !
