### ISSUE TITLE
Cannot use asset from outside my shared project

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#312]
I shared with myself an asset coming from a project that I don't own. When I copy/paste the link in the EE asset widget, it search for the name and then flush it. 

I guess there is some verification mechanism in the background that remove the provided name. I checked with a dummy one and I don't see the error message either. 

try to fill the field with a dummy name and you'll see it disapear.

<img width="173" alt="image" src="https://github.com/openforis/sepal/assets/12596392/91bf9167-fcb3-4f7a-a006-5d9ee9f64b64">

**Comment by cdanielw** [comment]
Invalid and not accessible assets are not cleared from the input anymore.
