### ISSUE TITLE
project name can be duplicated 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#320]
I managed to create a duplicated project which can lead to many issues like splitting your recipies in 2 differnt places by accident: 

<img width="960" alt="image" src="https://github.com/openforis/sepal/assets/12596392/f969ee96-8104-4fa0-9642-d52d989f1dac">

Can you enforce uniqueness of the project names ?

**Comment by dfguerrerom** [comment]
fixed in #327 , we will validate the project names before adding them and now we'll show the number of recipes in each projects

![image](https://github.com/user-attachments/assets/3b29b2b2-c5b7-4333-b9ca-73ff9595b710)
