### ISSUE TITLE
Add SSL Certificate to sepal.io

### ISSUE THREAD

**Issue by Davidezrajay** [openforis/sepal#44]
Site not secure: sepal.io

**Comment by Davidezrajay** [comment]
Looks like this is in the works already: https://github.com/openforis/sepal/blob/c2007b23956e8a7be388c5a7625ce33d499f86d5/docs/architecture-diagrams.pdf

**Comment by eriklindquist** [comment]
We had a security certificate renewal issue. We are working to manually update the certificate.
