### ISSUE TITLE
impossible to select all the dates in the dense-series datepicker in the french version 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#56]
When creating a new dense time serie, after you select your AOI, you're supposed to select the dates. 
To help end user (avoid people using wrong format), clicking on the date input open a small datepicker widget on the center of the screen.

When I proceed, some of the dates of the month are disabled. let's say that the cutting of the 30-31 days of the month is performed in a strange way. 

On this screenshot, the top values are from November and I cannot select any date after Christmas. 
![Capture d’écran 2020-10-21 à 14 16 40](https://user-images.githubusercontent.com/12596392/97312711-1439df80-1866-11eb-9106-7b510bda0ec2.png)

 
@yfinegold tested on her own account and she's not experiencing the problem and the only difference is that mine is in french

**Comment by lecrabe** [comment]
I re that bug from Pierrick. Reported this morning by Ivory Coast user to me also, definitely some weird rendering of dates in the French agenda version

**Comment by cdanielw** [comment]
I've replicated this, so it hopefully is easy enough to sort out.

**Comment by cdanielw** [comment]
There was a bug for locales where the week isn't starting on Sunday.
