### ISSUE TITLE
Jupyter Notebook Creating folder failed 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#58]
When creating a new folder from the Jupyter notebook interface, we get the following error : 

![Capture d’écran 2020-11-17 à 10 20 03](https://user-images.githubusercontent.com/12596392/99371094-c2adcf00-28be-11eb-9283-c5fe4737e80c.png)

If we refresh the page, the folder was in fact created under the name 'Untitled folder'.
Normally we should get a pop up windows to select a name before it's creation.

**Comment by cdanielw** [comment]
All requests to a sandbox are proxied. The proxy rewrite any location headers included in responses. When creating a folder in Jupyter, a 201 Created response, is returned, containing a location header pointing to the new folder. We get an error when rewriting this location. It seems like the location has not been URL encoded by Jupyter. The space is causing the issue. I would argue this is a bug on their end. In any case, I will do the URL encoding on my end, when location headers are malformatted.
