### ISSUE TITLE
automatically update modules

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#60]
At the moment the SEPAL modules are manually updated by the administrators of the plateform. Which means that every time you want to change the description, edit a typo, upload a hotfix, update a lib ... etc (let's say maintenance), you are forced to disturb Daniel or Erik.

It is effectively important to have administrators validation for the first push to the plateform, to avoid beeing flod by useless or unfinished modules. But once they have been uploaded once, the owner of the repository and/or the maintainers of the project are in best position to know when to push updates.

On the 2020-11-25 with @cdanielw we talked about two possible improvements :
•	listen to a specific branch of the modules (e.g. `release`) and automatically push changes when they occur
•	listen to the 'about' section of the repository so that the maintainers can change the description if needed

The administrators will still be in charge of the first push, the title and the keywords

I would like to have your thoughts about it

**Comment by eriklindquist** [comment]
Do I just reply to these messages here?
Or on slack?
Or where?

Lot's of messages coming from various platforms...

Erik Lindquist, PhD
Forestry Officer
National Forest Monitoring (NFM) Team
REDD+/NFM cluster, Forestry Department
Food and Agriculture Organization of the United Nations
Rome, Italy 00153
________________________________

**Comment by 12rambau** [comment]
@cdanielw the cron job that you set up worked on the Fragmentation modules, I'm closing the issue
