### ISSUE TITLE
lib installation for modules in SEPAL

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#62]
When creating new modules, we often need to install packages or libs that are not included in the build of SEPAL. 

## solution draft 

To avoid version bugs, we decided to start every module with the following cell : 

```py
%%capture
import sys
!{sys.executable} -m pip install --upgrade sepal-ui
!{sys.executable} -m pip install 'unidecode'
!{sys.executable} -m pip install 'pyperclip'
```

which was working nicely until now. 

## bugs

We now realize that it's a bad practice. for multiple reason :
- It slows down by several seconds the launch of or modules as it needs to perform installation in the background
-  @cdanielw have updated the `requirements.txt` of the sepal docker but the --user installed libs are never updated which recently lead to version conflict and crash of apps

## solution 

I should update the requirements.txt file with PR when really important libs need to be installed and remove the first cell of all our apps to only rely on the usr/ installed libs.

**Comment by 12rambau** [comment]
Now all user that have once used the python modules have a local installation of some libs that may be outdated now (ipyvuetify, sepal_ui, Wand...etc). 

In webinars we will for sure face this issue with users that have played with the dashboard tools. 3 solution if it occurs : 
- We ask them to open a terminal and type `$ rm -r ~/.local`
- I create a single btn app that execute this command 
- We drop the .local folder for all users (including developer as me that will be surprised to loose their custom libs)

@cdanielw @lecrabe What would you prefer ?

**Comment by cdanielw** [comment]
> We drop the .local folder for all users (including developer as me that will be surprised to loose their custom libs)

This is not an option. We need to allow users to install local packages.

> I create a single btn app that execute this command : drop_repository

The issue with this is that your app might not load at all if the user have conflicting versions of libraries.

> We ask them to open a terminal and type $ rm -r ~/.local

This works. Is ugly, confusing, and intrusive for user that actually need local Python libraries. But it works. 

Ideally, we would want apps started from the launchpad to disregard local libraries altogether. Jupyter and Jupyter Lab must, on the other hand, include them. Can we do this somehow?

**Comment by cdanielw** [comment]
Maybe we could have two separate kernels. One for Jupyter (Lab), including .local libs, and one for the notebook based apps, excluding .local libs.

**Comment by cdanielw** [comment]
The ideal solution would be if each of the apps had their own virtualenv, and a kernel configured for it. That way, each app could have their own libraries - no risk of conflict, and no need for Sepal re-deployment when these libs are updated. 

We would have to ensure:

- The kernels should not be visible from Jupyter and Jupyter Lab
   - That'd confuse users
   - It seems to be possible to hide kernels. Here's a post that try to show hidden kernels at least: https://stackoverflow.com/questions/50134013/locating-and-removing-hidden-kernels-in-jupyter-notebook
- Session startup cannot be slowed down too much
   - Libs must  be installed on the main server, and made available to session by an EFS (NFS) share
   - Must the kernel be installed before starting the Jupyter server? Is that slow? Is there another way to have a Voila app use a virtual env?

Pierrick, is this something you can start to investigate?

**Comment by 12rambau** [comment]
I'll investigate the implementation of a custom virtual env, I've also asked on SO if it's possible to only use the system installed packages.

**Comment by 12rambau** [comment]
I've received an answer from [SO](https://stackoverflow.com/questions/65306061/how-to-disregard-user-installed-libs?noredirect=1#comment115454891_65306061) which leads to an even simpler solution :

I just need to add the env variable `PYTHONNOUSERSITE`at the start of the kernel and normally it would just use non user libs (https://docs.python.org/3/using/cmdline.html#envvar-PYTHONNOUSERSITE).

I'll test it to confirm but it seems more reasonable and easy to use

**Comment by lecrabe** [comment]
Looks like a good one, we should do the same in R

**Comment by 12rambau** [comment]
**Quick update :** 

the `PYTHONNOUSERSITE` env variable need to be set prior to the start of the notebook so it won't work. diving into the [CLI doc](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONNOUSERSITE) I found out that you can discard the user installed lib using the `-s` option in Python

I tested it on my instances with a custom instalation of tqdm : 
```
$ python3 -s 
>>> import tqdm
>>> tqdm.__version__
'4.54.1'
>>> 

$ python3 
>>> import tqdm
>>> tqdm.__version__
'4.54.0'
>>> 
```
Good news it works. 

I think the best way to move forward is to create a custom kernel for app that runs in the dashboard with this `-s`option.  
 
Advantages :
-  costless
- easy to implement
- allow developers to test their module on the dashboard available lib to check  
    
Drawbacks: 
- I cannot test it myself as I don't have the right to write in the `usr/` folder (sorry @cdanielw)

**What we need to change**

first we need to create a new kernel in a `/usr/local/share/jupyter/kernels/dashboard` folder. We can copy/paste the `python3` one and keep the logos. 
We just need to change the kernel.json file into :
```json
{
 "argv": [
  "/usr/bin/python3",
  "-s",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Dashboard Python 3",
 "language": "python"
}
```

Once this kernel will be created (e.g. in test.env) I can verify it using the `jupyter console --kernel=dashboard`command and test it on actual notebooks

**run it for each app ?**

As I don't know (yet ?) how app are launched in the dashboard I cannot tell the next step. As extra information remember that : 
- we can save the release branch notebooks using this kernel (it will be the one used when laucnhed) 
- we can force the default kernel in the command line as : `jupyter notebook --MultiKernelManager.default_kernel_name=dashboard`

@cdanielw what do you think of this solution ?

**Comment by 12rambau** [comment]
## update

The selected solution is to create on the fly `venv`when the requirements.txt file is modified in the app repository. The only problem is now to enforce that the notebooks are effectively executed using the appropiate `venv`. 

I've asked to the voila team if they think of adding this parameters in url (https://github.com/voila-dashboards/voila/issues/967), I don't know if it's feasable or if they want to implement it. 

Quick reminder: in the metadata of the notebook, we want to change the following keys: 
```json
 "metadata": {
    "kernelspec": {
       "display_name": "Python 3",
       "language": "python",
       "name": "python3"
    },
}
```
@cdanielw can you remind me here what is the naming convention of the created venv/kernel ?

## solutions to explore

- [ ] Voila is willing to add this option in voila-dashboard url and I'll be glad to help them
- [ ] @cdanielw you can also modify the script to edit the ui.ipynb on pull. changing the metadata.kernelspec.name to the appropriate value.
- [ ] I can create a pre-commit hook that change the kernel before any push

What solution do you think is the most promising ?

**Comment by cdanielw** [comment]
Option 1 would be most flexible.

We should investigate if there's a way to have these kernels excluded from the kernel list within Jupyter and Lab. I though leaving out the `display_name` did that, but it turned out it's still there.

**Comment by 12rambau** [comment]
I think this is now covered:
modules include a requirements.txt file that is updating a specific venv within SEPAL this venv is used in the voila kernel when the application is launched. We still need some help from admins for the first loading but once it's there  apps developers are autonomous.
