### ISSUE TITLE
conflict in environment variables between rasterio and gdal 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#64]
## Context 
In sepal I only use Python3 through the jupyter notebook or JupyterLab app. 
In Python the [rasterio](https://github.com/mapbox/rasterio) lib offers access to all the [GDAL](https://github.com/OSGeo/gdal) operations in a more pythonic way than the gdal binding based on C code. 

A quick look into the GIS python community shows that developers prefer to use rasterio rather than the gdal binding for several reason listed in the [rasterio doc](https://rasterio.readthedocs.io/en/latest/topics/switch.html). 

In sepal, both rasterio and gdal are installed which leads to compatibility problem that I'd like to describe here. 

## Reproducible example 

```py 
import rasterio as rio 

rio.crs.CRS.from_epsg(4326)
```

you'll get the following error 
```python
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
Traceback (most recent call last):
  File "rasterio/_crs.pyx", line 279, in rasterio._crs._CRS.from_epsg
  File "rasterio/_err.pyx", line 190, in rasterio._err.exc_wrap_int
rasterio._err.CPLE_OpenFailedError: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/rasterio/crs.py", line 333, in from_epsg
    obj._crs = _CRS.from_epsg(code)
  File "rasterio/_crs.pyx", line 281, in rasterio._crs._CRS.from_epsg
rasterio.errors.CRSError: The EPSG code is unknown. Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
```

## Explanation 

This is a known issue of rasterio

Answers are given in many posts like these ones:
- [Where is “ERROR 4: Unable to open EPSG support file gcs.csv” coming from and what does it mean?](https://stackoverflow.com/questions/14444310/how-to-set-the-gdal-data-environment-variable-to-point-to-the-directory-containi/14465201#14465201)
- [How to set the GDAL_DATA environment variable to point to the directory containing EPSG csv files?](https://gis.stackexchange.com/questions/284709/error-4-unable-to-open-epsg-support-file-gcs-csv)
- ERROR 4: Unable to open EPSG support file gcs.csv
- [Unable to open EPSG support file gcs.csv #1539](https://github.com/mapbox/rasterio/issues/1539)
- [Missing gcs.csv file](https://inbo.github.io/niche_vlaanderen/faq.html#missing-gcs-csv-file)

In the sepal case the problem lies in the double installation of gdal (one for the gdal binding and one for the rasterio lib). 

if you play with your env: 
```py
import os 

print(os.environ['GDAL_DATA'])
print(os.environ['PROJ_LIB'])

>>> '/usr/share/gdal'
>>> '/usr/share/proj'
```

This path leads to the manual GDAL install that doesn't contains the gcs.csv file   
for rasterio to work it should point to: 
```
'/usr/local/lib/python3.6/dist-packages/rasterio/gdal_data'
'/usr/local/lib/python3.6/dist-packages/rasterio/proj_lib'
```

## Workaround 

The situation is not desperate as there is a small workaround that we found with @cdanielw. You need to delete the `GDAL_DATA` env in the first cell of your notebook or in the first lines of your python file:

```python 
import os 

if 'GDAL_DATA' in os.environ: 
    del os.environ['GDAL_DATA']

>>>

import rasterio as rio 

rio.crs.CRS.from_epsg(4326)

>>> CRS.from_epsg(4326)
```

but it's an ugly workaround that cannot apply to 3rd party libs such as [rasterstats](https://github.com/perrygeo/python-rasterstats) or [geocube](https://github.com/corteva/geocube) that are both based on the rasterio implementation of GDAL.

## Question 

Can we think of a more robust solution?

**Comment by 12rambau** [comment]
I need to check in an instance if copying the gdal data file can save us: 

```python 
mkdir /tmp/gdal_data
cp -r /usr/local/lib/python3.6/dist-packages/rasterio/gdal_data/ /tmp/gdal_data/
cp -r $GDAL_DATA/* /tmp/gdal_data/
```

then point to this file in my notebooks

**Comment by cdanielw** [comment]
Is this still a problem?

**Comment by 12rambau** [comment]
we found a workaround and there is no way we are removing GDAL from the system. So I've displayed this info in our doc. 
But lets keep it in our mind 100% sure it will come up again eventually
