### ISSUE TITLE
The terminal session is not displayed on safari

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#67]
This issue comes from Peter Vogt, he can't manage to display the terminal. When he start sepal the terminal tab leads to a black screen as here:  

![image](https://user-images.githubusercontent.com/12596392/107498418-0c434880-6b94-11eb-8cde-9dfe331aedbf.png)

Of course the problem is desapearing when he lanches sepal on other browsers (firefox and chrome have been tested)  

**set up**  
Safari: 14.0.3
OS: macOS Big Sur 11.2.1

**Comment by cdanielw** [comment]
I'm unable to replicate this. I'm running exactly the same Safari version and with Big Sur 11.2.2. Could this have been a temporary glitch, or maybe the user have some browser extensions interfering?

**Comment by vogtpet** [comment]
Confirm, this issue still exists on macOS 11.2.3, Safari 14.0.3 and no extensions active, also Safari -> Settings for this website... everything is allowed, still plain black. Chrome works fine.
![Screenshot 2021-03-11 at 17 05 41](https://user-images.githubusercontent.com/68806384/110817124-48012900-828c-11eb-8b9a-a1d230d88b0b.png)

**Comment by lpaolini** [comment]
This is weird. I'm running same versions of MacOS and Safari, without any custom settings.
There must be something interfering.

<img width="980" alt="Screenshot 2021-03-11 at 18 27 09" src="https://user-images.githubusercontent.com/377807/110828579-789a9000-8297-11eb-8baa-9ab3d389be7a.png">

**Comment by vogtpet** [comment]
Problem solved. This issue could be tracked down to our corporate proxy setup. Accessing the site with a regular internet connection works fine.
