### ISSUE TITLE
The file_input.vue has bee removed from the latest build

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#69]
In order to work the file_input widget require a `file_input.vue` in the `/usr/local/lib/python3.6/dist-packages/ipyvuetify/extra`.
Since the last build this file is missing. 

The error comes from the ipyvuetify lib, the file is not loaded during thre pip installation ([issue #124](https://github.com/mariobuikhuizen/ipyvuetify/issues/124)). 

Can we manually downgrade the ipyvuetify installation to 1.5.1 until Mario find a solution ?

**Comment by cdanielw** [comment]
Will be included in next release.

**Comment by 12rambau** [comment]
The problem have been solved in Ipyvuetify, In the next build you'll be able to let the automatic update to 1.6.2 (will be available in couple of days)
