### ISSUE TITLE
missing french translation message 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#72]
Lots of keys have been added to the dictionary since the last translation work

I'll shortly make a PR with an updated version of the fr dict.

**Comment by 12rambau** [comment]
@cdanielw I nearly finished the translation of all the french keys but I have extra questions concerning the english one : 

> cloudMasking.none.tooltip : "Use cloud-free pixels if possible, but don't mask areas without cloud-free pixels"
   
Does that means that we're using every pixel with or without cloud ? 

_______

> snowMasking.on.tooltip : "Mask snow. This tend to leave some pixels where with shadowy snow"  

This sentence doesn't seem english to me, is it ""Mask snow. This tend to leave some pixels with shadowy snow" ? 

________

> tasks.retrieve.creating_drive_folder: "Creating Google Drive Folders..."  

Plural or singular (the folder) because it's singular for deleting.

______

When @lecrabe did the first translation, they were  "[TODO] to be completed" in some key. Is it a special ignored str or should we avoid it ?

________

Last but not least : 

Several keys are now missing from the english dictionary. How can I remove them from the french one ?

**Comment by cdanielw** [comment]
See inlined in red
