### ISSUE TITLE
New version of sepal_ui 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#73]
I've build a new release of the [sepal_ui](https://github.com/12rambau/sepal_ui) lib : https://pypi.org/project/sepal-ui/
This version is correcting lots of bugs and introducing the new documentation : https://sepal-ui.readthedocs.io/en/latest/index.html

Would it be possible to rebuild Sepal to integrate this version ?

**to go further** 
For the modules there is a cron job listening to the repositories and update the version when a push is made on the `release` branch. 
The [sepal_ui](https://github.com/12rambau/sepal_ui) repository works the same way, the `release` branch reflects the latest published version on pypi. 
Would it be possible to wire a weekly cron job on the release branch of this repository so I stop bothering you when there is a new release ?

> If you are affraid by the code quality, the framework is 87% covered (https://codeclimate.com/github/12rambau/sepal_ui) so  retro-compatibility should not be a problem.

**Comment by 12rambau** [comment]
Also this new version embed the module factory python file that start a project from scratch with a module skeleton to save time. 

Can you add the `sepal_ui/bin` folder to the PATH so that any user can call the `module_factory` command as described in https://sepal-ui.readthedocs.io/en/latest/tutorials/create-module.html

**Comment by 12rambau** [comment]
a new way to update the sepal_ui lib have been found in https://github.com/openforis/sepal/commit/16270716ed52e4e51be86f876a98b8f90db9f430

**Comment by 12rambau** [comment]
`module_factory` is still not usable in SEPAL, is there any problem adding it to the PATH ?

**Comment by cdanielw** [comment]
> Also this new version embed the module factory python file that start a project from scratch with a module skeleton to save time.
> 
> Can you add the `sepal_ui/bin` folder to the PATH so that any user can call the `module_factory` command as described in https://sepal-ui.readthedocs.io/en/latest/tutorials/create-module.html

Can you provide the full absolute path of that directory from within the sandbox?

**Comment by 12rambau** [comment]
/usr/local/lib/python3.6/dist-packages/sepal_ui/bin/module_factory

**Comment by cdanielw** [comment]
I've added it to the focal branch, which will get merged into master soon.
