### ISSUE TITLE
Bug With JupyterLab build

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#78]
In the last build of SEAPL the JupyterLab version has changed and some of the build extention now bug. Here is a small list of the features that disapeared 

- As peter Vogt write in his email, Jupyterlab is asking for a rebuild 
![image](https://user-images.githubusercontent.com/12596392/110359380-b7350e00-803d-11eb-83fa-05818b58f783.png)

- The widget from ipyvuetify are not displayed when running notebook anymore. I may be linked to the rebuild of the extention list. We only get the following error message : `Error displaying widget: model not found`

**Comment by ingdanielguerrero** [comment]
Thanks for posting it here @12rambau, I'm also having that error, however ipywidgets widgets are still working.

**Comment by 12rambau** [comment]
Big thanks to @cdanielw for solving it.
