### ISSUE TITLE
Create a GWB module 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#80]
**What is the name of your repository ?**
https://github.com/12rambau/gwb

**the name of your dashboard app**
Guidos Workbench

**a short description of the app**
GWB is a subset of the desktop software package GuidosToolbox (GTB)

**any comment you want to add**
It is not requiring any libs. Some of the testers are not very aware of Git. would it be possible to set the `master` branch on the `test` env of SEPAL and the `release` one on the `prod`env ? 

**maintainer checklist**
- [x] Name is set 
- [x] Desccription set 
- [x] Comprehensive readme 
- [x] 3 languages docuentation files (can be empty)
- [x] The module works with the default availalbe python libs
- [x] Existence of a `release`branch 
- [x] check behaviour

**Comment by 12rambau** [comment]
sorry, I didn't ask for [@pertervogt](https://github.com/vogtpet) aproval before asking for the new GWB module. 


Would it be possible to change the title and description : 

|                      | old                                                                 | new                                                |  
|-------------|---------------------------------------------------------|-------------------------------------|
| title               | Guidos Workbench                                                    | GWB Analysis                                       |
| description  | GWB is a subset of the desktop software package GuidosToolbox (GTB) | A suite of various geospatial image analysis tools |

**Comment by cdanielw** [comment]
Done
