### ISSUE TITLE
install a copy/paste mechanism on sepal ?

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#81]
I would like to use the pyperclip lib in the sepal_ui lib. This Python lib mainly allows me to control the clipboard programatically. It would be extremelly useful when the outputs of the modules are link that you need to copy paste (any GEE asset). 

 **Is your feature request related to a problem? Please describe.**
When I use it on my local computer it works no problem but when I try it on SEPAL I get the following error : 

> PyperclipException: Pyperclip could not find a copy/paste mechanism for your system.

Based on the [documentation](https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error) SEPAL is missing a copy/paste mechanism

**Describe the solution you'd like**

According to the doc the solution could be to install a copy/paste mechanism from this list :
- [ ] `sudo apt-get install xsel` to install the xsel utility.
- [ ] `sudo apt-get install xclip` to install the xclip utility.
- [ ] `pip install gtk to install` the gtk Python module.
- [ ] `pip install PyQt4 to install` the PyQt4 Python module.

**note**
@cdanielw, I think it's typically the kind of bug that I can now handle myself. I will let you now in the comments if I find a solution

**Comment by cdanielw** [comment]
I assume pyperclip is about copy/paste for desktop applications - the APT dependencies certainly indicate that. You use Sepal either through a terminal or from a web browser. Managing the clipboard on the browser would be done with simple JavaScript code, rendered by your Jupyter Notebook.

**Comment by 12rambau** [comment]
yeah but it's really tricky to call js from a py file (I cannot use the Jupyter magic function) but that is where I'm heading effectively

**Comment by cdanielw** [comment]
Installing GTK and Qt related dependencies doesn't really make much sense on a non-desktop system.
