### ISSUE TITLE
remove the previous implementation of MSPA in the dashboard

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#83]
Now that the GWB module is set in the dashboard, [@vogtpet](https://github.com/vogtpet) suggested that we remove the previous implementation of mspa analysis. 

- The Python implementation **fragmentation map**: https://github.com/openforis/mspa-analysis
- The R implementation **Fragmentation map (R)**: https://github.com/openforis/sepal_mspa

@lecrabe do we have worflows that would force us to keep them ? (I would say no for the Python one but I don't know for R)

**Comment by cdanielw** [comment]
Can @lecrabe confirm that these two modules can be removed from test and prod?

**Comment by lecrabe** [comment]
@cdanielw & @12rambau yes confirmed, the GWB module covers already the functionalities in those initial modules. They can stay on the github repository for posterity.

**Comment by cdanielw** [comment]
Done
