### ISSUE TITLE
add a planet order module to the prod and test env

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#85]
**What is the name of your repository ?**  
https://github.com/12rambau/planet-order/

**The name of your dashboard app**  
PlanetLab order (beta)

**A short description of the app**  
Order imagery from PlanetLab mosaics

**Is your module requiring a GEE account ?**  
yes

**Any comment you want to add**  
Ok so this is a urgent requirement from @eriklindquist and @lecrabe for a presentation on monday. The tool is not 100% ready but if you install it now Rémi will be able to play with it this WE and I'll make the appropriate adjustments. 

Normally the `master` branch is already set-up on the test env, you'll just have to change the name and description to make it consistent with prod. On prod on the other hand You'll need to set-up the `release` branch ;-)  

In prod there is no need to add a `planet.key` file in the folder. people will use their own key. 

Problem: to work the module require the latest version of `sepal_ui`. I checked the [`requirement.txt`](https://github.com/openforis/sepal/blob/master/modules/geospatial-toolkit/docker/config/requirements.txt) file and the current version does not correspond (1.0.2) any idea how we could correct it ?  

**maintainer checklist**  
- [x] Name is set 
- [x] Desccription set 
- [x] Comprehensive readme 
- [x] 3 languages docuentation files (can be empty)
- [x] The module works with the default availalbe python libs
- [x] Existence of a `release`branch 
- [x] check behaviour

**Comment by 12rambau** [comment]
The module is now ready to go !

**Comment by cdanielw** [comment]
Done, but both master and release branches are giving errors.

**Comment by 12rambau** [comment]
is the sepal_ui version upgraded ?
