### ISSUE TITLE
Tropical Moist Forest

### ISSUE THREAD

**Issue by lecrabe** [openforis/sepal#86]
**What is the name of your repository ?**  
https://github.com/lecrabe/tmf_sepal

**The name of your dashboard app**  
Tropical Moist Forest

**A short description of the app**  
Wrapper for TMF

**Is your module requiring a GEE account ?**  
yes

**Any comment you want to add**  
Can you wire the release branch on the prod environment and the main branch on test

**maintainer checklist**  
- [x] Name is set 
- [x] Description set 
- [x] Comprehensive README
- [x] 3 languages documentation files (can be empty)
- [x] The module works with the default available python libs
- [x] Existence of a `release` branch 
- [x] Check behaviour

**Comment by cdanielw** [comment]
Done
