### ISSUE TITLE
Update Spanish translations for retrieve panel

### ISSUE THREAD

**Issue by cdanielw** [openforis/sepal#88]
There are new keys in the retrieve panel that needs Spanish translation.

**Comment by 12rambau** [comment]
we shouldn't work at the same time as the i18n program modify the 3 files at the same time. I'll create the keys in all languages, I'll let @daniel correct the typos in es. directly in the json

**Comment by cdanielw** [comment]
Alternatively, you could just commit the translation file for the language you've been working on. Then revert the changes to the other files.

**Comment by 12rambau** [comment]
I think we can do something even fancier, I'm getting my hand on the deepl API and read docs to see how we can wire it

**Comment by 12rambau** [comment]
@ingdanielguerrero when this PR will be merged (https://github.com/openforis/sepal/pull/89) You'll just have to modify the keys in the translation.json file (https://github.com/openforis/sepal/blob/master/modules/gui/frontend/src/locale/es/translations.json). 

the one that need translation are still in english. it was math and regression vocabulary, I have 0 clue on the translations (it was already super hard in French)

**Comment by ingdanielguerrero** [comment]
@12rambau perfect!, I'm gonna to wait for @cdanielw to merge your pr.
