### ISSUE TITLE
upgrade Python version 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#96]
IN SEPAL the current installed version of Python is 3.6.9 as default Python3. Python3.7 and Python3.8 are also installed but I don't knwo where they come from and they are not wired to the python3 command nor the jupyter kernels. According to the [documentation](https://endoflife.date/python) the end of support of 3.6 will be in 8 month. Some of the librairies that we use have already droped the use of 3.6 in their support including [numpy](https://numpy.org/news/) and [pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html). 

I've search in the code and their is no trace of a specific installation of Python3.6 so i assume it's a default behavior of Debian when in https://github.com/openforis/sepal/blob/master/deploy/Dockerfile we install Python3. 

I'm surprised beause Debian buster shoud come with the version 3.7.3 of Python by default (according to the [doc](https://packages.debian.org/buster/python3)). @cdanielw are we installing a specific version of debian ? 

> To go further on the python version issue, we should not change or upgrade the default version of Python in debian (I mean the Python3 command) without risking to break the installation. moving to the current default version is the only thing we can do. For the advance user we can still use pyenv.

**Comment by cdanielw** [comment]
We're running sandboxes with Ubuntu 18.04 (which we should upgrade to a later version - but that's a pain). I'll try to get a newer Python version up and running.

**Comment by 12rambau** [comment]
upgrading manually Python without ubuntu is a dangerous practice as set [here](https://dev.to/serhatteker/how-to-upgrade-to-python-3-7-on-ubuntu-18-04-18-10-5hab):

### Disclaimer
WARNING
Edited: 2020-12-28 16:53:45 UTC

Instead of using below method please consider adding a new/multi python version on your system. According the python version you want, look at one of the articles below:

How To Install Python 3.8 on Ubuntu
How To Install Python 3.9 on Ubuntu
Since below method may cause system error: probably break apt or misconfiguration of the system.

I think it's safer to just work on ubuntu 😄

**Comment by 12rambau** [comment]
done in https://github.com/openforis/sepal/commit/b62562f09d46e9aa23abaef0729b55610bfa0d74
