### ISSUE TITLE
Species validation tool 

### ISSUE THREAD

**Issue by t-elisee** [openforis/sepal#97]
**What is the name of your repository ?**  
https://github.com/openforis/shiny-species_validation.git 

**The name of your dashboard app**  
**Species validation tool** 

**A short description of the app**  
This tool can be used to validate a list containing trees' or plants' scientific names. 

**Is your module requiring a GEE account ?**  
NO 

**Any comment you want to add**  
library(leaflet)
library(shinydashboard)
library(collapsibleTree)
library(shinycssloaders)
library(DT)
library(tigris)
library(textclean)
library(shinyjs)   
library(DT)
library(shiny)
library(tidyverse)
library(leaflet.extras)
library(rvest)

**maintainer checklist**  
- [x] Name is set 
- [x] Description set 
- [x] Comprehensive README 
- [x] 3 languages documentation files (can be empty)
- [x] The module works with the default available Python libs
- [x] Existence of a `release` branch 
- [x] check behaviour

**Comment by 12rambau** [comment]
Can you provide the 3 documentation files somewhere in a docs folder of your repository. When the application will be pushed to the SEPAL prod env, these files will be automatically add to the [modules documentation space](https://docs.sepal.io/en/latest/modules/index.html). 

If you don't want to write anything, just copy paste the 3 doc files from this [folder](https://github.com/12rambau/sepal_ui_template/tree/master/doc) and replace the name at the top of each file and the link to your issue tracker

> note that I changed your initial comment, in markdown, to check boxes you just need to add a "x" like `[x]`

**Comment by cdanielw** [comment]
Is this ready to be put into prod?

**Comment by t-elisee** [comment]
We like to have it in the test environment

**Comment by cdanielw** [comment]
This isn't a public GitHub Repository. It there any reason to keep it private?

**Comment by t-elisee** [comment]
We are using private tokens in the app. We will like to test it first before sending it out

**Comment by cdanielw** [comment]
OK. I've added the app, but it will take some hours for the release needed with additional R packages.

**Comment by t-elisee** [comment]
An error has occurred!
there is no package called ‘tigris’
app can't be launched

**Comment by cdanielw** [comment]
Done
