### ISSUE TITLE
Tree DBH-Height Modelling Tool 

### ISSUE THREAD

**Issue by t-elisee** [openforis/sepal#98]
**What is the name of your repository ?**  
https://github.com/openforis/shiny-lmfor.git 

**The name of your dashboard app**  
**Tree DBH-Height Modelling Tool** 

**A short description of the app**  
The purpose on this tool is to provide an easy application for estimating relationship between tree breast height diameter (DBH) and top height by using ‘lmfor’ R-package

**Is your module requiring a GEE account ?**  
No

**Any comment you want to add**  
library('shinydashboard')
library('shinyBS') 
library('shinyjs') 
library('plotly')
library('tidyr')
library('dplyr')
library('lmfor')
library('ggplot2')
library('gridExtra')
library('grid') 
library('stringr')
library('png')
library('DT')
library('skimr')

**maintainer checklist**  
- [x] Name is set 
- [x] Description set 
- [x] Comprehensive README 
- [x] 3 languages documentation files (can be empty)
- [x] The module works with the default available Python libs
- [x] Existence of a `release` branch 
- [x] check behaviour

**Comment by 12rambau** [comment]
Can you provide the 3 documentation files somewhere in a docs folder of your repository. When the application will be pushed to the SEPAL prod env, these files will be automatically add to the [modules documentation space](https://docs.sepal.io/en/latest/modules/index.html). 

If you don't want to write anything, just copy paste the 3 doc files from this [folder](https://github.com/12rambau/sepal_ui_template/tree/master/doc) and replace the name at the top of each file and the link to your issue tracker

> note that I changed your initial comment, in markdown, to check boxes you just need to add a "x" like `[x]`

**Comment by cdanielw** [comment]
Done
